name: fmt

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - ".github/workflows/fmt.yml"
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - ".github/workflows/fmt.yml"

jobs:
  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout d2b-toolkit sibling
        run: git clone --depth 1 https://github.com/vicondoa/d2b-toolkit ../d2b-toolkit
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Build
        run: |
          source $HOME/.cargo/env
          cargo +nightly fmt --all -- --check

